---
title: "RSEAA 2022 Unconference experience"
description: |
  It was the first RSE online conference in the Asia Australia region. It was from 14-16 September 2022 at the Zoom Events. Here I will tell you the impression I got from it.
author:
  - name: Kozo Nishida
    url: https://github.com/kozo2/
preview: preview.png
date: 10-03-2022
base_url: https://rse-asia.github.io/RSE_Asia/
twitter:
  creator: "@RSE_Asia"
categories: [Research Software Engineering, Early Career Researcher, Mentorship]
output:
  distill::distill_article:
    self_contained: false
---

## Introduction

[The first RSE conference in the Asia Australia region](https://rse-aunz.github.io/2022-Asia-Australia-unconference/)
was held on 14 to 16 September 2022.
It was held online using the Zoom Events.

The content consisted of 3 keynote speeches, 1 panel discussions, and some discussion sessions on multiple themes in an unconference style.
The recordings of the keynotes and panel discussion can be watched on the following YouTube.

<iframe width="560" height="315" src="https://www.youtube.com/embed/EPHJhLgbK5w" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/VKH8RuSCq4c" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/Q4fR1RXydLw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/lN1GICnbohI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Accessibility and Inclusivity

The accessibility of the conference was excellent.
I'm Japanese and my English isn't very good.
But the conference has Zoom live transcription, which made it easy for me to understand what was being said.

To learn more about the accessibility, see [Liz Hare](https://twitter.com/DogGeneticsLLC)'s [high-level accessibility report for the conference](https://rse-aunz.github.io/RSEAUNZAccessibility.html).

## The Keynotes


## The unconference themes

## Conclusion

## Notes

- [Unconference website](https://rse-aunz.github.io/2022-Asia-Australia-unconference/)
- Twitter hashtag: [#RSEAA](https://twitter.com/hashtag/RSEAA)
